[DEBUG 18:34:49] git.util Failed checking if running in CYGWIN due to: FileNotFoundError(2, 'No such file or directory')
[DEBUG 18:34:49] git.cmd Popen(['git', 'diff', '--cached', '--abbrev=40', '--full-index', '--raw'], cwd=/home/ruanzhonghai/work/LAIES, universal_newlines=False, shell=None, istream=None)
[DEBUG 18:34:49] git.cmd Popen(['git', 'cat-file', '--batch-check'], cwd=/home/ruanzhonghai/work/LAIES, universal_newlines=False, shell=None, istream=<valid stream>)
[DEBUG 18:34:49] git.cmd Popen(['git', 'diff', '--cached', '--abbrev=40', '--full-index', '--raw'], cwd=/home/ruanzhonghai/work/LAIES, universal_newlines=False, shell=None, istream=None)
[DEBUG 18:34:49] git.cmd Popen(['git', 'cat-file', '--batch-check'], cwd=/home/ruanzhonghai/work/LAIES, universal_newlines=False, shell=None, istream=<valid stream>)
main.py:59: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.10 it will stop working
  if isinstance(v, collections.Mapping):
[INFO 18:34:49] root Saving to FileStorageObserver in /home/ruanzhonghai/work/results/sacred/5m_vs_6m/qmix_env=8_adam_td_lambda.
[DEBUG 18:34:50] pymarl Using capture mode "fd"
[INFO 18:34:50] pymarl Running command 'my_main'
[INFO 18:34:50] pymarl Started run with ID "8"
[DEBUG 18:34:50] pymarl Starting Heartbeat
[DEBUG 18:34:50] my_main Started
[INFO 18:34:50] my_main Experiment Parameters:
[INFO 18:34:50] my_main 

{   'GRF': False,
    'action_selector': 'epsilon_greedy',
    'agent': 'n_ncc',
    'agent_output_type': 'q',
    'alpha1': 0.1,
    'alpha2': 1,
    'anneal_intrin': 'Ture',
    'anneal_speed': 4000000,
    'batch_size': 128,
    'batch_size_run': 8,
    'beta1': 200,
    'beta2': 2,
    'buffer_cpu_only': True,
    'buffer_size': 5000,
    'checkpoint_path': '',
    'critic_lr': 0.0005,
    'cuda_num': 3,
    'cuda_save': True,
    'enemy_sample': 4,
    'enemy_shape': 3,
    'env': 'sc2',
    'env_args': {   'continuing_episode': False,
                    'debug': False,
                    'difficulty': '7',
                    'game_version': None,
                    'heuristic_ai': False,
                    'heuristic_rest': False,
                    'map_name': '5m_vs_6m',
                    'move_amount': 2,
                    'obs_all_health': True,
                    'obs_instead_of_state': False,
                    'obs_last_action': False,
                    'obs_own_health': True,
                    'obs_pathing_grid': False,
                    'obs_terrain_height': False,
                    'obs_timestep_number': False,
                    'replay_dir': '',
                    'replay_prefix': '',
                    'reward_death_value': 10,
                    'reward_defeat': 0,
                    'reward_negative_scale': 0.5,
                    'reward_only_positive': True,
                    'reward_scale': True,
                    'reward_scale_rate': 20,
                    'reward_sparse': False,
                    'reward_win': 200,
                    'seed': 125,
                    'state_last_action': True,
                    'state_timestep_number': False,
                    'step_mul': 8},
    'epsilon_anneal_time': 100000,
    'epsilon_finish': 0.05,
    'epsilon_start': 1.0,
    'evaluate': False,
    'gain': 0.01,
    'gamma': 0.99,
    'grad_norm_clip': 10,
    'hypernet_embed': 64,
    'i_one_clip': 0.002,
    'itrin_two_clip': 1,
    'label': 'CNCC_Dense',
    'learner': 'CNCC_SMAC',
    'learner_log_interval': 10000,
    'load_step': 0,
    'local_results_path': 'results',
    'log_interval': 10000,
    'lr': 0.001,
    'mac': 'ncc_mac',
    'mixer': 'qmix',
    'mixing_embed_dim': 32,
    'name': 'qmix_env=8_adam_td_lambda',
    'obs_agent_id': True,
    'obs_last_action': True,
    'optim_alpha': 0.99,
    'optim_eps': 1e-05,
    'optimizer': 'adam',
    'per_alpha': 0.6,
    'per_beta': 0.4,
    'predict_epoch': 25,
    'project_name': 'Lazy_Essay',
    'q_lambda': False,
    'repeat_id': 1,
    'return_priority': False,
    'rnn_hidden_dim': 64,
    'run': 'default',
    'runner': 'parallel',
    'runner_log_interval': 10000,
    'sample_size': 16,
    'save_model': False,
    'save_model_interval': 200000,
    'save_replay': True,
    'seed': 125,
    't_max': 15200000,
    'target_update_interval': 200,
    'td_lambda': 0.6,
    'test_greedy': True,
    'test_interval': 10000,
    'test_nepisode': 32,
    'use_cuda': True,
    'use_int': True,
    'use_layer_norm': False,
    'use_orthogonal': False,
    'use_per': False,
    'use_tensorboard': False,
    'wandb': True}

[DEBUG 18:34:50] git.cmd Popen(['git', 'rev-parse', '--show-toplevel'], cwd=/home/ruanzhonghai/work/LAIES, universal_newlines=False, shell=None, istream=None)
[DEBUG 18:34:51] urllib3.connectionpool Starting new HTTPS connection (1): api.wandb.ai:443
[DEBUG 18:34:51] urllib3.connectionpool https://api.wandb.ai:443 "POST /graphql HTTP/1.1" 200 None
[DEBUG 18:34:51] urllib3.connectionpool https://api.wandb.ai:443 "POST /graphql HTTP/1.1" 200 None
wandb: Currently logged in as: ruanzh (j). Use `wandb login --relogin` to force relogin
[DEBUG 18:34:51] git.cmd Popen(['git', 'cat-file', '--batch-check'], cwd=/home/ruanzhonghai/work/LAIES, universal_newlines=False, shell=None, istream=<valid stream>)
wandb: - Waiting for wandb.init()...wandb: \ Waiting for wandb.init()...wandb: | Waiting for wandb.init()...wandb: / Waiting for wandb.init()...wandb: - Waiting for wandb.init()...wandb: \ Waiting for wandb.init()...wandb: | Waiting for wandb.init()...wandb: / Waiting for wandb.init()...wandb: - Waiting for wandb.init()...wandb: \ Waiting for wandb.init()...wandb: | Waiting for wandb.init()...wandb: / Waiting for wandb.init()...wandb: - Waiting for wandb.init()...wandb: \ Waiting for wandb.init()...wandb: | Waiting for wandb.init()...wandb: / Waiting for wandb.init()...wandb: - Waiting for wandb.init()...wandb: \ Waiting for wandb.init()...wandb: | Waiting for wandb.init()...wandb: / Waiting for wandb.init()...wandb: - Waiting for wandb.init()...wandb: \ Waiting for wandb.init()...wandb: | Waiting for wandb.init()...wandb: / Waiting for wandb.init()...wandb: - Waiting for wandb.init()...wandb: \ Waiting for wandb.init()...wandb: | Waiting for wandb.init()...wandb: / Waiting for wandb.init()...wandb: - Waiting for wandb.init()...wandb: \ Waiting for wandb.init()...wandb: | Waiting for wandb.init()...wandb: / Waiting for wandb.init()...wandb: - Waiting for wandb.init()...wandb: \ Waiting for wandb.init()...wandb: | Waiting for wandb.init()...wandb: / Waiting for wandb.init()...wandb: - Waiting for wandb.init()...wandb: \ Waiting for wandb.init()...wandb: | Waiting for wandb.init()...wandb: / Waiting for wandb.init()...wandb: - Waiting for wandb.init()...wandb: \ Waiting for wandb.init()...wandb: | Waiting for wandb.init()...wandb: / Waiting for wandb.init()...wandb: - Waiting for wandb.init()...wandb: \ Waiting for wandb.init()...wandb: | Waiting for wandb.init()...wandb: / Waiting for wandb.init()...wandb: - Waiting for wandb.init()...wandb: \ Waiting for wandb.init()...wandb: | Waiting for wandb.init()...wandb: / Waiting for wandb.init()...wandb: - Waiting for wandb.init()...wandb: \ Waiting for wandb.init()...wandb: | Waiting for wandb.init()...wandb: / Waiting for wandb.init()...wandb: - Waiting for wandb.init()...wandb: \ Waiting for wandb.init()...wandb: | Waiting for wandb.init()...wandb: / Waiting for wandb.init()...wandb: - Waiting for wandb.init()...wandb: \ Waiting for wandb.init()...wandb: | Waiting for wandb.init()...wandb: / Waiting for wandb.init()...wandb: Network error (ReadTimeout), entering retry loop.
wandb: - Waiting for wandb.init()...wandb: \ Waiting for wandb.init()...wandb: | Waiting for wandb.init()...wandb: / Waiting for wandb.init()...wandb: - Waiting for wandb.init()...wandb: \ Waiting for wandb.init()...wandb: | Waiting for wandb.init()...wandb: / Waiting for wandb.init()...wandb: - Waiting for wandb.init()...wandb: \ Waiting for wandb.init()...wandb: | Waiting for wandb.init()...wandb: / Waiting for wandb.init()...wandb: - Waiting for wandb.init()...wandb: \ Waiting for wandb.init()...wandb: | Waiting for wandb.init()...wandb: / Waiting for wandb.init()...wandb: - Waiting for wandb.init()...wandb: \ Waiting for wandb.init()...wandb: | Waiting for wandb.init()...wandb: / Waiting for wandb.init()...wandb: - Waiting for wandb.init()...wandb: \ Waiting for wandb.init()...wandb: | Waiting for wandb.init()...wandb: / Waiting for wandb.init()...wandb: - Waiting for wandb.init()...[DEBUG 18:36:22] urllib3.connectionpool Starting new HTTPS connection (1): o151352.ingest.sentry.io:443
[DEBUG 18:36:22] urllib3.connectionpool https://o151352.ingest.sentry.io:443 "POST /api/4504800232407040/store/ HTTP/1.1" 200 0
Problem at: /home/ruanzhonghai/work/LAIES/runners/parallel_runner.py 56 __init__
/home/ruanzhonghai/.conda/envs/pymarl/lib/python3.8/site-packages/sacred/stdout_capturing.py:179: UserWarning: tee_stdout.wait timeout. Forcibly terminating.
  warnings.warn("tee_stdout.wait timeout. Forcibly terminating.")
/home/ruanzhonghai/.conda/envs/pymarl/lib/python3.8/site-packages/sacred/stdout_capturing.py:185: UserWarning: tee_stderr.wait timeout. Forcibly terminating.
  warnings.warn("tee_stderr.wait timeout. Forcibly terminating.")
[DEBUG 18:36:24] pymarl Stopping Heartbeat
[ERROR 18:36:24] pymarl Failed after 0:01:34!
Traceback (most recent calls WITHOUT Sacred internals):
  File "main.py", line 38, in my_main
    run_REGISTRY[_config['run']](_run, config, _log)
  File "/home/ruanzhonghai/work/LAIES/run/run.py", line 54, in run
    run_sequential(args=args, logger=logger)
  File "/home/ruanzhonghai/work/LAIES/run/run.py", line 87, in run_sequential
    runner = r_REGISTRY[args.runner](args=args, logger=logger)
  File "/home/ruanzhonghai/work/LAIES/runners/parallel_runner.py", line 56, in __init__
    wandb.init(project=args.project_name, name=wandb_name, group=map_name, job_type=job_type, config=args)
  File "/home/ruanzhonghai/.conda/envs/pymarl/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 1184, in init
    raise e
  File "/home/ruanzhonghai/.conda/envs/pymarl/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 1165, in init
    run = wi.init()
  File "/home/ruanzhonghai/.conda/envs/pymarl/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 780, in init
    raise error
wandb.errors.CommError: Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-

[DEBUG 18:36:26] urllib3.connectionpool https://o151352.ingest.sentry.io:443 "POST /api/4504800232407040/envelope/ HTTP/1.1" 200 0
